SEED_DESTINATIONS = [
    {
        "slug": "bali-indonesia",
        "city": "Bali",
        "country": "Indonesia",
        "cost_index": 0.85,
        "currency_code": "IDR",
        "facts": {
            "attractions": [
                {"name": "Ubud Monkey Forest", "area": "Ubud", "note": "Sacred forest sanctuary; watch belongings."},
                {"name": "Tegallalang Rice Terraces", "area": "Ubud", "note": "Go early to avoid tour-bus crowds."},
                {"name": "Tanah Lot Temple", "area": "Tabanan", "note": "Sea temple best at late afternoon."},
                {"name": "Uluwatu Temple", "area": "Uluwatu", "note": "Cliff-side sunset and kecak dance."},
                {"name": "Seminyak Beach", "area": "Seminyak", "note": "Beach clubs and sunset walks."},
                {"name": "Tirta Empul", "area": "Tampaksiring", "note": "Holy spring water temple; bring a sarong."},
                {"name": "Nusa Penida day trip", "area": "Nusa Penida", "note": "Kelingking viewpoint; seas can be rough."},
                {"name": "Campuhan Ridge Walk", "area": "Ubud", "note": "Easy sunrise ridge trail."},
            ],
            "neighborhoods": [
                {"name": "Ubud", "vibe": "Culture, rice fields, yoga, quieter nights."},
                {"name": "Canggu", "vibe": "Surf, cafes, coworking, livelier nightlife."},
                {"name": "Seminyak", "vibe": "Walkable beach, restaurants, mid-range stays."},
                {"name": "Uluwatu", "vibe": "Cliffs, surf breaks, more spread out."},
            ],
            "localTips": [
                "Temple visits require a sarong covering knees and shoulders.",
                "Scooters are common but traffic and insurance are real risks — use drivers if unsure.",
                "Nyepi (Day of Silence) shuts the island; do not plan arrivals that day.",
                "Cash is still useful for small warungs; ATMs are widely available in tourist areas.",
            ],
            "stayIdeas": {
                "backpacker": ["A social hostel in Canggu", "A guesthouse near Ubud center"],
                "comfort": ["A boutique hotel in Seminyak", "A rice-field view hotel on the edge of Ubud"],
                "luxury": ["A clifftop resort in Uluwatu", "A private-pool villa in Seminyak"],
            },
        },
    },
    {
        "slug": "tokyo-japan",
        "city": "Tokyo",
        "country": "Japan",
        "cost_index": 1.6,
        "currency_code": "JPY",
        "facts": {
            "attractions": [
                {"name": "Senso-ji", "area": "Asakusa", "note": "Oldest temple; Nakamise street for snacks."},
                {"name": "Shibuya Crossing", "area": "Shibuya", "note": "Best viewed from a nearby upper floor."},
                {"name": "Meiji Shrine", "area": "Harajuku", "note": "Forest walk from Harajuku station."},
                {"name": "teamLab Planets", "area": "Toyosu", "note": "Book timed tickets; you will get wet."},
                {"name": "Tsukiji Outer Market", "area": "Tsukiji", "note": "Breakfast tamagoyaki and street food."},
                {"name": "Tokyo Skytree", "area": "Sumida", "note": "Go on a clear day for Mt. Fuji views."},
                {"name": "Akihabara", "area": "Akihabara", "note": "Electronics, anime, themed cafes."},
                {"name": "Imperial Palace East Garden", "area": "Chiyoda", "note": "Free, closed Mondays and Fridays."},
            ],
            "neighborhoods": [
                {"name": "Shinjuku", "vibe": "Transit hub, nightlife, every budget of food."},
                {"name": "Shibuya", "vibe": "Youth culture, shopping, busy evenings."},
                {"name": "Asakusa", "vibe": "Old Tokyo, temples, calmer stays."},
                {"name": "Ginza", "vibe": "Upscale shopping and dining."},
            ],
            "localTips": [
                "Get a Suica or Pasmo (or the phone equivalent) on day one.",
                "Tipping is not expected and can confuse staff.",
                "Convenience stores (7-Eleven, FamilyMart) are genuinely good for meals.",
                "Trains stop around midnight — plan last trains or a late-night taxi budget.",
            ],
            "stayIdeas": {
                "backpacker": ["A capsule hotel in Shinjuku", "A hostel in Asakusa"],
                "comfort": ["A business hotel near a JR Yamanote station", "A mid-range hotel in Shibuya"],
                "luxury": ["A luxury hotel in Ginza", "A high-rise hotel in Shinjuku with city views"],
            },
        },
    },
    {
        "slug": "lisbon-portugal",
        "city": "Lisbon",
        "country": "Portugal",
        "cost_index": 1.15,
        "currency_code": "EUR",
        "facts": {
            "attractions": [
                {"name": "Belém Tower", "area": "Belém", "note": "Combine with Jerónimos Monastery and pastel de nata."},
                {"name": "Jerónimos Monastery", "area": "Belém", "note": "Buy timed tickets; Mondays some sites close."},
                {"name": "Alfama", "area": "Alfama", "note": "Tram 28, miradouros, fado at night."},
                {"name": "LX Factory", "area": "Alcântara", "note": "Converted industrial complex of shops and food."},
                {"name": "Time Out Market", "area": "Cais do Sodré", "note": "Many kitchens under one roof — go off-peak."},
                {"name": "Castelo de São Jorge", "area": "Castelo", "note": "Hilltop castle with city views."},
                {"name": "Sintra day trip", "area": "Sintra", "note": "Pena Palace and Quinta da Regaleira; start early."},
                {"name": "MAAT", "area": "Belém", "note": "Contemporary art on the river."},
            ],
            "neighborhoods": [
                {"name": "Baixa / Chiado", "vibe": "Central, walkable, tourist-heavy but convenient."},
                {"name": "Alfama", "vibe": "Hills, tiles, fado, fewer chain hotels."},
                {"name": "Bairro Alto / Príncipe Real", "vibe": "Nightlife and independent shops."},
                {"name": "Cais do Sodré", "vibe": "River, bars, Time Out Market."},
            ],
            "localTips": [
                "Hills are steep — wear decent shoes and use trams/elevadors strategically.",
                "Pickpockets work tram 28 and viewpoints; keep bags zipped.",
                "Many museums close on Mondays.",
                "A Viva Viagem card covers metro, tram, and some trains.",
            ],
            "stayIdeas": {
                "backpacker": ["A hostel in Bairro Alto", "A guesthouse in Alfama"],
                "comfort": ["A tiled townhouse hotel in Chiado", "A 4 star hotel near Baixa-Chiado metro"],
                "luxury": ["A palacete hotel in Príncipe Real", "A river-view luxury hotel in Chiado"],
            },
        },
    },
    {
        "slug": "paris-france",
        "city": "Paris",
        "country": "France",
        "cost_index": 1.8,
        "currency_code": "EUR",
        "facts": {
            "attractions": [
                {"name": "Eiffel Tower", "area": "7th", "note": "Book summit/tickets; Trocadéro for the classic view."},
                {"name": "Louvre", "area": "1st", "note": "Timed entry; pick a wing rather than trying to see all."},
                {"name": "Musée d'Orsay", "area": "7th", "note": "Impressionists in a former station; closed Mondays."},
                {"name": "Notre-Dame exterior & Île de la Cité", "area": "4th", "note": "Walk the island and Sainte-Chapelle nearby."},
                {"name": "Sacré-Cœur & Montmartre", "area": "18th", "note": "Go early before portrait-painter crowds."},
                {"name": "Sainte-Chapelle", "area": "1st", "note": "Stained glass — buy a combined Conciergerie ticket."},
                {"name": "Le Marais", "area": "3rd/4th", "note": "Food, Place des Vosges, Jewish quarter history."},
                {"name": "Versailles day trip", "area": "Versailles", "note": "RER C; gardens are half the visit."},
            ],
            "neighborhoods": [
                {"name": "Le Marais", "vibe": "Walkable, cafes, independent shops."},
                {"name": "Saint-Germain", "vibe": "Classic Left Bank, bookshops, bistros."},
                {"name": "Montmartre", "vibe": "Hills, village feel, busier at Sacré-Cœur."},
                {"name": "Latin Quarter", "vibe": "Students, cheap eats, near islands."},
            ],
            "localTips": [
                "A Navigo Easy or weekly Navigo pass is cheaper than per-ride tickets for dense days.",
                "Many museums are closed Tuesdays (Louvre) or Mondays (Orsay) — check before you queue.",
                "Reservations matter for popular restaurants; walk-ins work better at lunch.",
                "Tap water is fine; ask for une carafe d'eau.",
            ],
            "stayIdeas": {
                "backpacker": ["A hostel in the Latin Quarter", "A budget hotel near République"],
                "comfort": ["A boutique hotel in Le Marais", "A 4 star hotel in Saint-Germain"],
                "luxury": ["A palace hotel near Place Vendôme", "A luxury Left Bank hotel with courtyard"],
            },
        },
    },
    {
        "slug": "bangkok-thailand",
        "city": "Bangkok",
        "country": "Thailand",
        "cost_index": 0.75,
        "currency_code": "THB",
        "facts": {
            "attractions": [
                {"name": "Grand Palace & Wat Phra Kaew", "area": "Rattanakosin", "note": "Dress code strictly enforced; go at opening."},
                {"name": "Wat Arun", "area": "Thonburi", "note": "Cross by ferry from the Grand Palace side."},
                {"name": "Wat Pho", "area": "Rattanakosin", "note": "Reclining Buddha and optional massage school."},
                {"name": "Chatuchak Weekend Market", "area": "Chatuchak", "note": "Sat–Sun only; go in the morning."},
                {"name": "Jim Thompson House", "area": "Pathum Wan", "note": "Teak houses and silk history."},
                {"name": "Lumpini Park", "area": "Pathum Wan", "note": "Monitor lizards, lakeside paths, early mornings."},
                {"name": "Chinatown (Yaowarat)", "area": "Samphanthawong", "note": "Street food after dark."},
                {"name": "Ayutthaya day trip", "area": "Ayutthaya", "note": "Train north; rent a bike among the ruins."},
            ],
            "neighborhoods": [
                {"name": "Sukhumvit", "vibe": "BTS access, restaurants, mixed budgets."},
                {"name": "Old City / Rattanakosin", "vibe": "Temples, hostels, slower nights."},
                {"name": "Silom", "vibe": "Business district, river access, food."},
                {"name": "Ari", "vibe": "Cafes, local feel, a short BTS hop from the center."},
            ],
            "localTips": [
                "BTS/MRT plus river boats beat sitting in traffic.",
                "Temple dress code: covered shoulders and knees; scarves are sold at gates.",
                "The King's anthem plays in cinemas and some public places — stand still.",
                "Street food is often the best meal; look for busy stalls.",
            ],
            "stayIdeas": {
                "backpacker": ["A hostel on Khao San Road", "A guesthouse near a BTS station on Sukhumvit"],
                "comfort": ["A 4 star hotel on Sukhumvit with a pool", "A riverside hotel in Silom"],
                "luxury": ["A luxury riverside hotel with a boat shuttle", "A 5 star hotel near Siam"],
            },
        },
    },
    {
        "slug": "santorini-greece",
        "city": "Santorini",
        "country": "Greece",
        "cost_index": 1.7,
        "currency_code": "EUR",
        "facts": {
            "attractions": [
                {"name": "Oia sunset", "area": "Oia", "note": "Extremely crowded; arrive early or watch from a side street."},
                {"name": "Fira", "area": "Fira", "note": "Caldera rim walk toward Firostefani."},
                {"name": "Amoudi Bay", "area": "Oia", "note": "Stairs down from Oia for seafood by the water."},
                {"name": "Red Beach", "area": "Akrotiri", "note": "Short visit; check rockfall notices."},
                {"name": "Akrotiri archaeological site", "area": "Akrotiri", "note": "Bronze Age town preserved in volcanic ash."},
                {"name": "Pyrgos", "area": "Pyrgos", "note": "Hill village with fewer cruise-day crowds."},
                {"name": "Perissa / Perivolos beach", "area": "South", "note": "Black sand, sunbeds, more space than the caldera."},
                {"name": "Caldera hike Fira to Oia", "area": "Caldera", "note": "3–4 hours; bring water and a hat."},
            ],
            "neighborhoods": [
                {"name": "Fira", "vibe": "Transit hub, mixed budgets, nightlife."},
                {"name": "Oia", "vibe": "Postcard views, expensive, crowded at sunset."},
                {"name": "Imerovigli", "vibe": "Quieter caldera, Skaros rock."},
                {"name": "Perissa", "vibe": "Beach stays, better value than the rim."},
            ],
            "localTips": [
                "ATV rentals look fun and cause many injuries — a small car is safer.",
                "Cruise-ship days crush Oia; plan interior villages then.",
                "Caldera hotels often include breakfast with the view — worth it on comfort/luxury.",
                "Ferries and flights fill in peak summer; lock transport early.",
            ],
            "stayIdeas": {
                "backpacker": ["A simple hotel in Fira town", "A rooms-to-let stay in Perissa"],
                "comfort": ["A caldera-view hotel in Firostefani", "A cave-style hotel in Imerovigli"],
                "luxury": ["A suite hotel in Oia with an outdoor hot tub", "A luxury caldera resort in Imerovigli"],
            },
        },
    },
    {
        "slug": "dubai-uae",
        "city": "Dubai",
        "country": "UAE",
        "cost_index": 1.9,
        "currency_code": "AED",
        "facts": {
            "attractions": [
                {"name": "Burj Khalifa", "area": "Downtown", "note": "Book At the Top timed tickets; sunset sells out."},
                {"name": "Dubai Mall fountain show", "area": "Downtown", "note": "Free; evenings are cooler."},
                {"name": "Dubai Marina walk", "area": "Marina", "note": "Evening promenade and boat options."},
                {"name": "Old Dubai: Al Fahidi & Creek", "area": "Bur Dubai", "note": "Abra crossing and spice/gold souks."},
                {"name": "Museum of the Future", "area": "Emirates Towers", "note": "Architecture is the attraction; book ahead."},
                {"name": "Desert safari (licensed operator)", "area": "Desert", "note": "Dune dinner tours — pick a reputable firm."},
                {"name": "Jumeirah Mosque", "area": "Jumeirah", "note": "Open to non-Muslim visitors on guided tours."},
                {"name": "La Mer / Kite Beach", "area": "Jumeirah", "note": "Beach time outside the mall circuit."},
            ],
            "neighborhoods": [
                {"name": "Downtown Dubai", "vibe": "Burj, mall, metro, polished."},
                {"name": "Dubai Marina", "vibe": "High-rises, walkable waterfront."},
                {"name": "Deira / Bur Dubai", "vibe": "Older city, souks, better food value."},
                {"name": "Jumeirah", "vibe": "Beach, mosques, lower-rise."},
            ],
            "localTips": [
                "Metro + tram covers a surprising amount; taxis/Careem fill the gaps.",
                "Dress more modestly in Old Dubai and malls than on hotel beaches.",
                "Friday is the start of the weekend; some attractions have different hours.",
                "Summer (Jun–Sep) is extremely hot — plan indoor midday and outdoor dawn/dusk.",
            ],
            "stayIdeas": {
                "backpacker": ["A budget hotel near a metro station in Deira", "A no-frills hotel in Bur Dubai"],
                "comfort": ["A 4 star hotel in Downtown or Business Bay", "A Marina hotel with a pool"],
                "luxury": ["A 5 star hotel on Palm Jumeirah", "A luxury Downtown hotel facing the fountain"],
            },
        },
    },
    {
        "slug": "new-york-usa",
        "city": "New York",
        "country": "USA",
        "cost_index": 2.1,
        "currency_code": "USD",
        "facts": {
            "attractions": [
                {"name": "Central Park", "area": "Manhattan", "note": "Walk a slice (The Mall, Bethesda, Bow Bridge) rather than all of it."},
                {"name": "The Metropolitan Museum of Art", "area": "Upper East Side", "note": "Pay-what-you-wish for NY State residents; others have a set fee."},
                {"name": "High Line & Chelsea Market", "area": "Chelsea / Meatpacking", "note": "Walk south to north to hit Chelsea Market at the end."},
                {"name": "Statue of Liberty / Ellis Island", "area": "Harbor", "note": "Ferry tickets in advance; crown access is separate."},
                {"name": "Brooklyn Bridge walk", "area": "DUMBO / Civic Center", "note": "Start in Brooklyn at sunrise for fewer people."},
                {"name": "MoMA", "area": "Midtown", "note": "Free Friday evenings; otherwise book."},
                {"name": "9/11 Memorial", "area": "Financial District", "note": "The memorial plaza is free; museum is ticketed."},
                {"name": "A Broadway show", "area": "Times Square / Theatre District", "note": "TKTS booth or lottery apps for cheaper seats."},
            ],
            "neighborhoods": [
                {"name": "Lower East Side / East Village", "vibe": "Food, bars, smaller hotels."},
                {"name": "Williamsburg", "vibe": "Brooklyn, waterfront, nightlife."},
                {"name": "Midtown", "vibe": "Transit, tourist density, convenient for first-timers."},
                {"name": "Upper West Side", "vibe": "Near the park, residential, quieter nights."},
            ],
            "localTips": [
                "OMNY / MetroCard on buses and subway; avoid taxi-only days in traffic.",
                "Walking is often faster than a crosstown cab.",
                "Many museums are closed or have odd hours on Mondays — check.",
                "Outer-borough food (Queens, Brooklyn) is often better value than Manhattan.",
            ],
            "stayIdeas": {
                "backpacker": ["A hostel on the Lower East Side", "A budget hotel in Midtown near a subway"],
                "comfort": ["A 4 star hotel in Chelsea or Midtown", "A boutique hotel in the East Village"],
                "luxury": ["A luxury Midtown hotel", "A high-end hotel in SoHo or the West Village"],
            },
        },
    },
]
